### PR TITLE
Update interpolate_curve.m

### PR DESCRIPTION
**Pull request by IRRer-Zins**
matlab compability caused by no automatic broadcasting

### CODE REVIEW

**Comment by Schinzilord** [comment]
Hi! Nice implementation, nearly no impact on performance at all (+0.2s for a vector of 5000000 rates). Do you want to make additional changes? Just say when you are ready, then I will merge your changes.

**Comment by Schinzilord** [comment]
There has to be the possibility to specify arbitrary number of terms. The for loop is around 60% slower than with automatic broadcasting, and with

```
Terms = repmat(Terms,rows(Values),1);
```

it is around 30% slower.. Is repmat available for Matlab?
Is something like rows or columns available for Matlab?

**Comment by IRRer-Zins** [comment]
repmat works in Matlab.
rows(xxxxx) is equal to Matlab: size(xxxxx,1)
columns(xxxxx) is equal to Matlab: size(xxxxx,2)

**Comment by Schinzilord** [comment]
Thanks your pointing to this incompatibility!
I took over the repmat solution and added comments.
Since there is a performance disadvantage of using repmat in Octave, the code can be uncommented for usage in Matlab.

**Pull request closed without merging**
