### PR TITLE
Matlab adaption

### PR DESCRIPTION
**Pull request by IRRer-Zins**
Date format compatibility for Matlab: Scalar instead of vector format.

### CODE REVIEW

**Comment by Schinzilord** [comment]
Why is there a incompatibility due to vector dateformat instead of datestr? Do you use the daysact function from Matlabs Financial Toolbox?  In line 106 it should be dat**e**str.

**Comment by Schinzilord** [comment]
What do you think about skipping the daysact function comletely? I had a look at it, and the whole function can be replaced by a simple 

```
if  years1 == years2  %coupon period in between one year
            dip = datenum(dvec2) - datenum(dvec1);  
            dib = yeardays(years1,basis);
        elseif  years2 > years1
            end_of_year_period1 = [years1,12,31,0,0,0];
            yeardays(years1,basis);
            begin_of_year_period2 = [years2,01,01,0,0,0];
            yeardays(years2,basis);
            days_period1 = datenum(end_of_year_period1) - datenum(dvec1);
            days_period2 = datenum(dvec2) - datenum(begin_of_year_period2) + 1;
            dib = 1;
            dip = (days_period1 ./ yeardays(years1,basis)) + (days_period2 ./ yeardays(years2,basis)) + (years2 - years1 - 1);
        else    % no timefactor for negative time period
            dip = 0;
            dib = 1;
        end
```

where just a difference in datenums is calculated, thus gaining some milliseconds.
What do you think about that?

**Comment by IRRer-Zins** [comment]
Yes, it's daysact function from Financial Toolbox.
Without datestr, you get an output vector [Y,M,D,H,MN,S] with octarisk's inputformat,
with datestr, you get an output scalar [D].
Octave can handle both input formats to an output scalar [D].
line 106 has been corrected to datestr.

**Comment by IRRer-Zins** [comment]
a more simple code is possible, for "improved" performance.
I will look at it later.

**Pull request closed without merging**
